-- Drop existing tables and enum safely
DROP TABLE IF EXISTS public.subtasks CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TYPE IF EXISTS public."Priority";

-- Recreate ENUM
CREATE TYPE public."Priority" AS ENUM (
    'HIGH',
    'MEDIUM',
    'LOW'
);

-- Recreate tasks table
CREATE TABLE public.tasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    description text,
    completed boolean DEFAULT false NOT NULL,
    priority public."Priority" DEFAULT 'MEDIUM' NOT NULL,
    category text DEFAULT 'General' NOT NULL,
    "dueDate" timestamp(3),
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp(3) NOT NULL
);

-- Recreate subtasks table
CREATE TABLE public.subtasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    completed boolean DEFAULT false NOT NULL,
    "taskId" integer NOT NULL,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT subtasks_taskId_fkey FOREIGN KEY ("taskId")
        REFERENCES public.tasks(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Insert data for tasks
INSERT INTO public.tasks
(id, title, description, completed, priority, category, "dueDate", "createdAt", "updatedAt")
VALUES
(1, 'テストタスク', 'テストタスクの説明', false, 'LOW', 'Work',
 '2026-07-21 00:00:00', '2026-07-18 22:20:48.248', '2026-07-18 22:23:14.25');

-- Insert data for subtasks
INSERT INTO public.subtasks
(id, title, completed, "taskId", "createdAt")
VALUES
(1, 'テストチェックリスト１', true, 1, '2026-07-18 22:22:42.528'),
(2, 'テストチェックリスト２', true, 1, '2026-07-18 22:22:51.06'),
(3, 'テストチェックリスト３', false, 1, '2026-07-18 22:23:00.564');

-- Fix sequences
SELECT pg_catalog.setval('public.tasks_id_seq', 1, true);
SELECT pg_catalog.setval('public.subtasks_id_seq', 3, true);
